// <auto-generated />
using CatalogoDeArmas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CatalogoDeArmas.Migrations.Arma
{
    [DbContext(typeof(ArmaContext))]
    [Migration("20201024172235_ArmaTableMigration")]
    partial class ArmaTableMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CatalogoDeArmas.Models.Arma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Img")
                        .HasColumnType("varchar(250");

                    b.Property<int>("Nombre")
                        .HasColumnType("varchar(250");

                    b.HasKey("Id");

                    b.ToTable("Armas");
                });
#pragma warning restore 612, 618
        }
    }
}
